{{- if .Values.gateway.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gateway.serviceAccount.name }}
  labels:
    app: {{ .Values.gateway.serviceAccount.name }}
  {{- with .Values.gateway.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.gateway.serviceAccount.automount }}
{{- end }}
