apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-order-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-order-service
spec:
  {{- if not .Values.order.autoscaling.enabled }}
  replicas: {{ .Values.order.replicas }}
  {{- end }}

  {{- with .Values.order.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  selector:
    matchLabels:
      app: {{ .Chart.Name }}-order-service

  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-order-service

    spec:
      serviceAccountName: {{ .Values.order.serviceAccount.name }}

      {{- with .Values.order.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}-order-service
          image: "{{ .Values.order.image.repository }}:{{ .Values.order.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.order.image.pullPolicy }}

          {{- with .Values.order.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          ports:
            - name: http
              containerPort: {{ .Values.order.service.targetPort }}
              protocol: TCP

          {{- with .Values.order.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.order.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.order.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.order.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.order.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      {{- with .Values.order.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.order.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.order.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.order.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
