apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.order.service.port }}
      targetPort: {{ .Values.order.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}-order-service