services:

  product-service:
    image: rupesh1997/product-service:1.0.2
    container_name: product-service
    ports:
      - "8181:8181"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8181/actuator/health/readiness" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    extends:
      file: common-config.yaml
      service: network-configuration

  order-service:
    image: rupesh1997/order-service:1.0.2
    container_name: order-service
    ports:
      - "8282:8282"
    depends_on:
      product-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      PRODUCT_SERVICE_BASE_PATH: http://product-service:8181
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8282/actuator/health/readiness" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    extends:
      file: common-config.yaml
      service: network-configuration

  ecm-frontend-svc:
    image: rupesh1997/ecm-frontend-svc:1.0.0
    container_name: ecm-frontend-svc
    ports:
      - "8080:80"
    depends_on:
      order-service:
        condition: service_healthy
    extends:
      file: common-config.yaml
      service: network-configuration

networks:
  ecm-ms:
    driver: bridge