apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: ecm

spec:
  selector:
    app: config-deployment
  ports:
    - port: 8071
      targetPort: 8071
      protocol: TCP
  type: LoadBalancer