apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: ecm

spec:
  selector:
    app: config-server-deployment
  ports:
    - port: 8071
      targetPort: 8071
      protocol: TCP
  type: LoadBalancer