apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: ecm

spec:
  selector:
    app: discovery-server-deployment
  ports:
    - port: 8070
      targetPort: 8070
      protocol: TCP
  type: LoadBalancer