apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  namespace: ecm

spec:
  selector:
    app: gateway-server-deployment
  ports:
    - port: 8072
      targetPort: 8072
      protocol: TCP
  type: LoadBalancer