apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server-deployment
  namespace: ecm
  labels:
    app: gateway-server-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server-deployment
  template:
    metadata:
      labels:
        app: gateway-server-deployment
    spec:
      containers:
        - name: gateway-server-deployment
          image: "rupesh1997/gateway-server:1.0.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 8072
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
            - name: ALLOWED_CORS_ORIGINS
              value: "http://34.47.217.79:8080"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://34.47.217.79:8070/eureka/"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
