apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecm

spec:
  selector:
    app: order-svc-deployment
  ports:
    - port: 8282
      targetPort: 8282
      protocol: TCP
  type: LoadBalancer