apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-svc-deployment
  namespace: ecm
  labels:
    app: product-svc-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-svc-deployment
  template:
    metadata:
      labels:
        app: product-svc-deployment
    spec:
      containers:
        - name: product-svc-deployment
          image: "rupesh1997/product-service:1.0.2"
          imagePullPolicy: Always
          ports:
            - containerPort: 8181
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://34.47.217.79:8070/eureka/"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
